server:
  port: 8081

spring:
  application:
    name: sentinel-client-1
  cloud:
    sentinel:
      transport:
        port: 8720
        dashboard: 127.0.0.1:8090

eureka:
  instance:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
